language: bash

dist: xenial

cache: apt

script:
  # install emacs
  - sudo add-apt-repository ppa:kelleyk/emacs --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs26-nox bibtex2html
  - sudo ln -sf /usr/bin/emacs26 /usr/bin/emacs
  - emacs --version
  # build HTML
  - emacs -l ./install.el --batch
  - ./export_all.sh
  - echo '!*.html' >> .gitignore

deploy:
  provider: pages
  target-branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: dev
