addons:
  apt:
    packages:
      - emacs-nox
      - bibtex2html

cache: apt

script:
  - ./install.el
  - ./export_all.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
