dist: xenial

addons:
  apt:
    packages:
      - emacs

cache: apt

script:
  - emacs --version
  - wget http://www.lri.fr/~filliatr/ftp/bibtex2html/bibtex2html-1.99-linux.tar.gz
  - tar -xf bibtex2html-1.99-linux.tar.gz
  - export PATH=`pwd`/bibtex2html-1.99-linux:$PATH
  - ./install.el
  - ./export_all.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
